INSERT INTO CITY (NAME) VALUES ('Stockholm');
INSERT INTO CITY (NAME) VALUES ('Göteborg');
INSERT INTO CITY (NAME) VALUES ('Malmö');
INSERT INTO CITY (NAME) VALUES ('Uppsala');
INSERT INTO CITY (NAME) VALUES ('Luleå');
INSERT INTO CITY (NAME) VALUES ('Karlstad');
INSERT INTO CITY (NAME) VALUES ('Örebro');
INSERT INTO CITY (NAME) VALUES ('Kristianstad');
INSERT INTO CITY (NAME) VALUES ('Halmstad');
INSERT INTO CITY (NAME) VALUES ('Västerås');
INSERT INTO CITY (NAME) VALUES ('Åre');
INSERT INTO CITY (NAME) VALUES ('Karlskrona');
INSERT INTO CITY (NAME) VALUES ('Linköping');
INSERT INTO CITY (NAME) VALUES ('Sundsvall');
INSERT INTO CITY (NAME) VALUES ('Visby');


INSERT INTO COURSE (TITLE, START_DATE, GRADUATION_DATE) VALUES ('Java HT 2022', '01-08-2022', '21-10-2022');
INSERT INTO COURSE (TITLE, START_DATE, GRADUATION_DATE) VALUES ('JavaScript HT 2022', '01-08-2022', '21-10-2022');

INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES ('Johan', 'Mattsson', 'johan@mail.com','123');
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES ('Carl', 'Norrland', 'carl@mail.com','123');